# SPDX-FileCopyrightText: 2024 Dan Anglin <d.n.i.anglin@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
version: "2"
run:
  concurrency: 2
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
linters:
  default: all
  disable:
  - exhaustruct
  - gosec
  - mnd
  - tagliatelle
  settings:
    depguard:
      rules:
        main:
          files:
          - $all
          allow:
          - $gostd
          - codeflow.dananglin.me.uk/apollo/enbas
    lll:
      line-length: 140
  exclusions:
    generated: lax
    presets:
    - comments
    - common-false-positives
    - legacy
    - std-error-handling
    paths:
    - third_party$
    - builtin$
    - examples$
formatters:
  enable:
  - gci
  - gofmt
  - gofumpt
  - goimports
  exclusions:
    generated: lax
    paths:
    - third_party$
    - builtin$
    - examples$
