# SPDX-FileCopyrightText: 2024 Dan Anglin <d.n.i.anglin@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

version                      = 1
SPDX-PackageName             = "enbas"
SPDX-PackageSupplier         = "Dan Anglin <d.n.i.anglin@gmail.com>"
SPDX-PackageDownloadLocation = "https://codeflow.dananglin.me.uk/apollo/enbas"

[[annotations]]
path = [
    "**.go",
    "go.mod",
    "magefiles/go.mod",
    "cmd/enbas-codegen/templates/**/*.go.gotmpl",
    "schema/enbas_cli_schema.json",
    ".forgejo/workflows/*.yaml",
    ".forgejo/actions/**/action.yaml",
    ".forgejo/actions/**/Dockerfile",
    "internal/utilities/testdata/statuses/*.txt",
]
precedence              = "override"
SPDX-FileCopyrightText  = "2024 Dan Anglin <d.n.i.anglin@gmail.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
    "README.md",
    "docs/*.md",
    "assets/images/*.png",
]
precedence              = "override"
SPDX-FileCopyrightText  = "2024 Dan Anglin <d.n.i.anglin@gmail.com>"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = [
    "go.sum",
    "magefiles/go.sum",
]
precedence              = "override"
SPDX-FileCopyrightText  = "2024 Dan Anglin <d.n.i.anglin@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"
