---
name: CI

on:
  pull_request:
    branches:
    - main
    types:
    - opened
    - synchronize

jobs:
  tests:
    name: Tests
    if: ${{ ! github.event.pull_request.draft }}
    runs-on: docker
    steps:
    - name: Checkout Repository
      uses: https://code.forgejo.org/actions/checkout@v4
    - name: Run tests
      uses: https://codeflow.dananglin.me.uk/actions/mage-ci@main
      with:
        target: test
      env:
        ENBAS_TEST_VERBOSE: "1"
        ENBAS_TEST_COVER: "1"
    - name: Run gosec
      uses: https://codeflow.dananglin.me.uk/actions/mage-ci@main
      with:
        target: gosec
    - name: Run go vet
      uses: https://codeflow.dananglin.me.uk/actions/mage-ci@main
      with:
        target: govet

  style:
    name: Style
    if: ${{ ! github.event.pull_request.draft }}
    runs-on: docker
    steps:
    - name: Checkout Repository
      uses: https://code.forgejo.org/actions/checkout@v4
    - name: Check formatting
      uses: https://codeflow.dananglin.me.uk/actions/mage-ci@main
      with:
        target: gofmt
      env:
        ENBAS_FAIL_ON_FORMATTING: "1"
    - name: Run staticcheck
      uses: https://codeflow.dananglin.me.uk/actions/mage-ci@main
      with:
        target: staticcheck

  reuse:
    name: REUSE Compliance Check
    runs-on: docker
    steps:
    - name: Checkout Repository
      uses: https://code.forgejo.org/actions/checkout@v4
    - name: REUSE Compliance Check
      uses: https://github.com/fsfe/reuse-action@v4
