// SPDX-FileCopyrightText: 2024 Dan Anglin <d.n.i.anglin@gmail.com>
//
// SPDX-License-Identifier: GPL-3.0-or-later

package executor

const (
	flagAccountName       = "account-name"
	flagBrowser           = "browser"
	flagContentType       = "content-type"
	flagContent           = "content"
	flagEnableFederation  = "enable-federation"
	flagEnableLikes       = "enable-likes"
	flagEnableReplies     = "enable-replies"
	flagEnableReposts     = "enable-reposts"
	flagFrom              = "from"
	flagFromFile          = "from-file"
	flagInstance          = "instance"
	flagLanguage          = "language"
	flagLimit             = "limit"
	flagListID            = "list-id"
	flagListTitle         = "list-title"
	flagListRepliesPolicy = "list-replies-policy"
	flagMyAccount         = "my-account"
	flagNotify            = "notify"
	flagSensitive         = "sensitive"
	flagSkipRelationship  = "skip-relationship"
	flagShowPreferences   = "show-preferences"
	flagShowReposts       = "show-reposts"
	flagSpoilerText       = "spoiler-text"
	flagStatusID          = "status-id"
	flagTag               = "tag"
	flagTimelineCategory  = "timeline-category"
	flagTo                = "to"
	flagType              = "type"
	flagVisibility        = "visibility"

	resourceAccount   = "account"
	resourceBlocked   = "blocked"
	resourceBookmarks = "bookmarks"
	resourceFollowers = "followers"
	resourceFollowing = "following"
	resourceInstance  = "instance"
	resourceLike      = "like"
	resourceLiked     = "liked"
	resourceList      = "list"
	resourceNote      = "note"
	resourceStatus    = "status"
	resourceStar      = "star"
	resourceStarred   = "starred"
	resourceTimeline  = "timeline"
)
