package executor

const (
	flagFrom string = "from"
	flagTo   string = "to"
	flagType string = "type"

	resourceAccount         string = "account"
	resourceBlocked         string = "blocked"
	resourceBookmarks       string = "bookmarks"
	resourceBoost           string = "boost"
	resourceFollowers       string = "followers"
	resourceFollowing       string = "following"
	resourceFollowRequest   string = "follow-request"
	resourceFollowedTags    string = "followed-tags"
	resourceInstance        string = "instance"
	resourceLike            string = "like"
	resourceLiked           string = "liked"
	resourceList            string = "list"
	resourceMedia           string = "media"
	resourceMediaAttachment string = "media-attachment"
	resourceMutedAccounts   string = "muted-accounts"
	resourceNote            string = "note"
	resourceNotifications   string = "notifications"
	resourcePoll            string = "poll"
	resourceStatus          string = "status"
	resourceStar            string = "star"
	resourceStarred         string = "starred"
	resourceTag             string = "tag"
	resourceThread          string = "thread"
	resourceTimeline        string = "timeline"
	resourceVote            string = "vote"
)
