/*
   This file is generated by the code generator.
   DO NOT EDIT.
*/

package executor

import "codeflow.dananglin.me.uk/apollo/enbas/internal/cli"

// TargetFuncMap returns a map of the targets and their
// associated targetFunc.
func targetFuncMap() map[string]targetFunc {
	return map[string]targetFunc{
		cli.TargetAccess:          accessFunc,
		cli.TargetAccount:         accountFunc,
		cli.TargetAccounts:        accountsFunc,
		cli.TargetBlockedAccounts: blockedAccountsFunc,
		cli.TargetBookmarks:       bookmarksFunc,
		cli.TargetConfig:          configFunc,
		cli.TargetFavourites:      favouritesFunc,
		cli.TargetFollowRequest:   followRequestFunc,
		cli.TargetFollowRequests:  followRequestsFunc,
		cli.TargetFollowers:       followersFunc,
		cli.TargetFollowings:      followingsFunc,
		cli.TargetHelp:            helpFunc,
		cli.TargetInstance:        instanceFunc,
		cli.TargetList:            listFunc,
		cli.TargetLists:           listsFunc,
		cli.TargetMedia:           mediaFunc,
		cli.TargetMediaAttachment: mediaAttachmentFunc,
		cli.TargetMutedAccounts:   mutedAccountsFunc,
		cli.TargetNote:            noteFunc,
		cli.TargetNotification:    notificationFunc,
		cli.TargetNotifications:   notificationsFunc,
		cli.TargetServer:          serverFunc,
		cli.TargetStatus:          statusFunc,
		cli.TargetTag:             tagFunc,
		cli.TargetTags:            tagsFunc,
		cli.TargetThread:          threadFunc,
		cli.TargetTimeline:        timelineFunc,
		cli.TargetVersion:         versionFunc,
		cli.TargetVotes:           votesFunc,
	}
}
