/*
   This file is generated by the code generator.
   DO NOT EDIT.
*/

package cli

const (
	ActionAccept      string = "accept"
	ActionAdd         string = "add"
	ActionBlock       string = "block"
	ActionClear       string = "clear"
	ActionCreate      string = "create"
	ActionDelete      string = "delete"
	ActionEdit        string = "edit"
	ActionFavourite   string = "favourite"
	ActionFind        string = "find"
	ActionFollow      string = "follow"
	ActionInvalidate  string = "invalidate"
	ActionMute        string = "mute"
	ActionReblog      string = "reblog"
	ActionReject      string = "reject"
	ActionRemove      string = "remove"
	ActionRename      string = "rename"
	ActionShow        string = "show"
	ActionStart       string = "start"
	ActionSwitch      string = "switch"
	ActionUnblock     string = "unblock"
	ActionUnfavourite string = "unfavourite"
	ActionUnfollow    string = "unfollow"
	ActionUnmute      string = "unmute"
	ActionUnreblog    string = "unreblog"
	ActionVerify      string = "verify"
)

// IsAction returns true if the parameter is an existing action.
func IsAction(action string) bool {
	_, result := actionSet()[action]

	return result
}

// actionSet returns a set of existing actions.
func actionSet() map[string]struct{} {
	return map[string]struct{}{
		ActionAccept:      {},
		ActionAdd:         {},
		ActionBlock:       {},
		ActionClear:       {},
		ActionCreate:      {},
		ActionDelete:      {},
		ActionEdit:        {},
		ActionFavourite:   {},
		ActionFind:        {},
		ActionFollow:      {},
		ActionInvalidate:  {},
		ActionMute:        {},
		ActionReblog:      {},
		ActionReject:      {},
		ActionRemove:      {},
		ActionRename:      {},
		ActionShow:        {},
		ActionStart:       {},
		ActionSwitch:      {},
		ActionUnblock:     {},
		ActionUnfavourite: {},
		ActionUnfollow:    {},
		ActionUnmute:      {},
		ActionUnreblog:    {},
		ActionVerify:      {},
	}
}
