/*
   This file is generated by the code generator.
   DO NOT EDIT.
*/

package cli

// BuiltInAlias returns the command corresponding to the
// requested built-in alias.
func BuiltInAlias(alias string) ([]string, bool) {
	cmd, ok := builtInAliasMap()[alias]

	return cmd, ok
}

// builtInAliasMap returns a map of the built-in aliases.
func builtInAliasMap() map[string][]string {
	return map[string][]string{
		"help": {
			"show",
			"usage",
		},
		"login": {
			"create",
			"access",
		},
		"version": {
			"show",
			"version",
		},
		"whoami": {
			"verify",
			"access",
		},
	}
}
