/*
   This file is generated by the code generator.
   DO NOT EDIT.
*/

package cli

const (
	TargetAccess          string = "access"
	TargetAccount         string = "account"
	TargetAccounts        string = "accounts"
	TargetAlias           string = "alias"
	TargetAliases         string = "aliases"
	TargetBlockedAccounts string = "blocked-accounts"
	TargetBookmarks       string = "bookmarks"
	TargetConfig          string = "config"
	TargetFavourites      string = "favourites"
	TargetFilter          string = "filter"
	TargetFilterKeyword   string = "filter-keyword"
	TargetFilterStatus    string = "filter-status"
	TargetFilters         string = "filters"
	TargetFollowRequest   string = "follow-request"
	TargetFollowRequests  string = "follow-requests"
	TargetFollowers       string = "followers"
	TargetFollowings      string = "followings"
	TargetInstance        string = "instance"
	TargetList            string = "list"
	TargetLists           string = "lists"
	TargetMedia           string = "media"
	TargetMediaAttachment string = "media-attachment"
	TargetMutedAccounts   string = "muted-accounts"
	TargetNote            string = "note"
	TargetNotification    string = "notification"
	TargetNotifications   string = "notifications"
	TargetServer          string = "server"
	TargetStatus          string = "status"
	TargetTag             string = "tag"
	TargetTags            string = "tags"
	TargetThread          string = "thread"
	TargetTimeline        string = "timeline"
	TargetToken           string = "token"
	TargetTokens          string = "tokens"
	TargetUsage           string = "usage"
	TargetVersion         string = "version"
	TargetVotes           string = "votes"
)

// TargetActionPreposition returns the preposition word used to
// relate the focused target to another target.
func TargetActionPreposition(target, action string) string {
	return targetActionPrepositionMap()[target+"-"+action]
}

func targetActionPrepositionMap() map[string]string {
	return map[string]string{
		TargetAccess + "-" + ActionSwitch:     "to",
		TargetAccounts + "-" + ActionAdd:      "to",
		TargetAccounts + "-" + ActionRemove:   "from",
		TargetFilterKeyword + "-" + ActionAdd: "to",
		TargetFilterStatus + "-" + ActionAdd:  "to",
		TargetFollowers + "-" + ActionShow:    "from",
		TargetFollowings + "-" + ActionShow:   "from",
		TargetMedia + "-" + ActionShow:        "from",
		TargetNote + "-" + ActionAdd:          "to",
		TargetNote + "-" + ActionRemove:       "from",
		TargetStatus + "-" + ActionAdd:        "to",
		TargetStatus + "-" + ActionRemove:     "from",
		TargetThread + "-" + ActionShow:       "from",
		TargetVotes + "-" + ActionAdd:         "to",
	}
}
