/*
   This file is generated by the enbas-codegen
   DO NOT EDIT.
*/

package usage

var summaries = map[string]string{
	"accept":   "Accepts a request (e.g. a follow request)",
	"add":      "Adds a resource to another resource",
	"block":    "Blocks a resource (e.g. an account)",
	"create":   "Creates a specific resource",
	"delete":   "Deletes a specific resource",
	"edit":     "Edit a specific resource",
	"follow":   "Follow a resource (e.g. an account)",
	"init":     "Creates a new configuration file in the specified configuration directory",
	"login":    "Logs into an account on GoToSocial",
	"mute":     "Mutes a specific resource (e.g. an account)",
	"reject":   "Rejects a request (e.g. a follow request)",
	"remove":   "Removes a resource from another resource",
	"server":   "Runs Enbas in server mode",
	"show":     "Shows details about a specified resource",
	"switch":   "Performs a switch operation (e.g. switching between logged in accounts)",
	"unblock":  "Unblocks a resource (e.g. an account)",
	"unfollow": "Unfollows a resource (e.g. an account)",
	"unmute":   "Umutes a specific resource (e.g. an account)",
	"version":  "Prints the application's version and build information",
	"whoami":   "Prints the account that you are currently logged into",
}
